/**
 * Publisher Factory
 *
 */
//
var templeteHTML = '';
templeteHTML += '    <div class="container" style="position: absolute;left: 0;top: 0;right: 0;bottom: 0;z-index: 1000;background: #fffffff0;width: 100%;height: 100%; margin:0;max-width: none; overflow:auto;">';
templeteHTML += '        <div class="py-5 text-center">';
templeteHTML += '           <h3>Mongburim Bot 사용에 관한 책임 안내</h3>';
templeteHTML += '           <div class="row">';
templeteHTML += '               <p class="lead" style="font-size:18px;">';
templeteHTML += '                   시세봇 사용자는 사용에 관한 모든 책임이 사용자에게 있다는 것을 인지하고, 시세봇을 사용하는 것에 동의합니다. 시세봇은 네이버 부동산의 오픈된 API를 이용하지만 승인(개발자 센터 오픈API)는 아닌 API를 사용하여 시세정보를 가져옵니다. 네이버 약관에 이러한 형태에 대해 명확하게 사용 및 금지조항이 없어 시세봇을 사용하면서 발생되는 문제에 대해서는 사용자에게 모든 책임이 있다는 것을 인지하고 시세봇을 사용하는 것에 동의합니다.';
templeteHTML += '               </p>';
templeteHTML += '               <div class="custom-control custom-checkbox" style="margin:0 auto;">';
templeteHTML += '                   <input type="checkbox" class="custom-control-input" id="isAgree">';
templeteHTML += '                   <label class="custom-control-label" for="isAgree">시세봇 사용책임 동의</label>';
templeteHTML += '               </div>';
templeteHTML += '           </div>';
templeteHTML += '        </div>';
templeteHTML += '        <div class="row" id="botProgress" style="display:block;padding:0 30px;">';
templeteHTML += '            <h4 class="d-flex justify-content-between align-items-center mb-3" >';
templeteHTML += '                <span class="text-muted" style="font-size: 18px;">bot message</span>';
templeteHTML += '                <span class="badge badge-secondary badge-pill" id="complexCount">0/0</span>';
templeteHTML += '            </h4>';
templeteHTML += '            <div class="progress" style="margin-bottom:45px;">';
templeteHTML += '                <div id="complexProgress" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>';
templeteHTML += '            </div>';
templeteHTML += '        </div>';
templeteHTML += '        <div class="row">';
templeteHTML += '            <div class="col-md-4 order-md-2 mb-4">';
templeteHTML += '                <h4 class="d-flex justify-content-between align-items-center mb-3">';
templeteHTML += '                    <span class="text-muted">Complex Count </span>';
templeteHTML += '                    <span class="badge badge-secondary badge-pill" id="complexCount">0/12</span>';
templeteHTML += '                </h4>';
templeteHTML += '                <div class="custom-control custom-checkbox" style="margin:10px;">';
templeteHTML += '                    <input type="checkbox" class="custom-control-input" value="all" id="sec-all">';
templeteHTML += '                    <label class="custom-control-label" for="sec-all">전체선택/해제</label>';
templeteHTML += '                </div>';
templeteHTML += '                <div style="max-height: 393px;overflow:auto;">';
templeteHTML += '                    <ul class="list-group mb-3" id="secList">';
templeteHTML += '                    </ul>';
templeteHTML += '                </div>';
templeteHTML += '            </div>';
templeteHTML += '            <div class="col-md-8 order-md-1">';
templeteHTML += '                <h4 class="mb-3" id="regionTitle">지역을 동단위로 선택해 주세요!</h4>';
templeteHTML += '                <form class="needs-validation" novalidate="" name="botCondition">';
templeteHTML += '                    <div class="row">';
templeteHTML += '                        <div class="col-md-6 mb-3">';
templeteHTML += '                            <label for="country">시도</label>';
templeteHTML += '                            <select class="custom-select d-block w-100" id="citySelector" disabled="">';
templeteHTML += '                                <option value="0">Choose..</option>';
templeteHTML += '                            </select>';
templeteHTML += '                        </div>';
templeteHTML += '                        <div class="col-md-6 mb-3">';
templeteHTML += '                            <label for="state">시군구</label>';
templeteHTML += '                            <select class="custom-select d-block w-100" id="dvsnSelector" disabled="">';
templeteHTML += '                                <option value="0">Choose..</option>';
templeteHTML += '                            </select>';
templeteHTML += '                        </div>';
templeteHTML += '                    </div>';
templeteHTML += '                    <hr class="mb-4">';
templeteHTML += '                    <div class="row">';
templeteHTML += '                        <div class="col-md-4 mb-3" id="areaCondition">';
templeteHTML += '                            <h4 class="mb-3">면적</h4>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="area-all" checked="true">';
templeteHTML += '                                <label class="custom-control-label" for="area-all">전체</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="area0py" target="areaChk">';
templeteHTML += '                                <label class="custom-control-label" for="area0py">~10평</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="area10py" target="areaChk">';
templeteHTML += '                                <label class="custom-control-label" for="area10py">10평대</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="area20py" target="areaChk">';
templeteHTML += '                                <label class="custom-control-label" for="area20py">20평대</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="area30py" target="areaChk">';
templeteHTML += '                                <label class="custom-control-label" for="area30py">30평대</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="area40py" target="areaChk">';
templeteHTML += '                                <label class="custom-control-label" for="area40py">40평대</label>';
templeteHTML += '                            </div>';
templeteHTML += '                        </div>';
templeteHTML += '                        <div class="col-md-4 mb-3">';
templeteHTML += '                            <h4 class="mb-3">세대수</h4>';
templeteHTML += '                            <div class="d-block my-3">';
templeteHTML += '                                <div class="custom-control custom-radio">';
templeteHTML += '                                    <input id="household-all" name="household" value="0" type="radio" class="custom-control-input">';
templeteHTML += '                                    <label class="custom-control-label" for="household-all">전체</label>';
templeteHTML += '                                </div>';
templeteHTML += '                                <div class="custom-control custom-radio">';
templeteHTML += '                                    <input id="household-100" name="household" value="100" type="radio" class="custom-control-input">';
templeteHTML += '                                    <label class="custom-control-label" for="household-100">100세대 이상</label>';
templeteHTML += '                                </div>';
templeteHTML += '                                <div class="custom-control custom-radio">';
templeteHTML += '                                    <input id="household-200" name="household" value="200" type="radio" class="custom-control-input" checked="true">';
templeteHTML += '                                    <label class="custom-control-label" for="household-200">200세대 이상</label>';
templeteHTML += '                                </div>';
templeteHTML += '                                <div class="custom-control custom-radio">';
templeteHTML += '                                    <input id="household-300" name="household" value="300" type="radio" class="custom-control-input">';
templeteHTML += '                                    <label class="custom-control-label" for="household-300">300세대 이상</label>';
templeteHTML += '                                </div>';
templeteHTML += '                                <div class="custom-control custom-radio">';
templeteHTML += '                                    <input id="household-400" name="household" value="400" type="radio" class="custom-control-input">';
templeteHTML += '                                    <label class="custom-control-label" for="household-400">400세대 이상</label>';
templeteHTML += '                                </div>';
templeteHTML += '                                <div class="custom-control custom-radio">';
templeteHTML += '                                    <input id="household-500" name="household" value="500" type="radio" class="custom-control-input">';
templeteHTML += '                                    <label class="custom-control-label" for="household-500">500세대 이상</label>';
templeteHTML += '                                </div>';
templeteHTML += '                            </div>';
templeteHTML += '                        </div>';
templeteHTML += '                        <div class="col-md-4 mb-3" id="roomCondition">';
templeteHTML += '                            <h4 class="mb-3">방개수</h4>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="room-all" checked="true">';
templeteHTML += '                                <label class="custom-control-label" for="room-all">전체</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="room1" target="roomChk">';
templeteHTML += '                                <label class="custom-control-label" for="room1">방1개</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="room2" target="roomChk">';
templeteHTML += '                                <label class="custom-control-label" for="room2">방2개</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="room3" target="roomChk">';
templeteHTML += '                                <label class="custom-control-label" for="room3">방3개</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="room4" target="roomChk">';
templeteHTML += '                                <label class="custom-control-label" for="room4">방4개</label>';
templeteHTML += '                            </div>';
templeteHTML += '                            <div class="custom-control custom-checkbox">';
templeteHTML += '                                <input type="checkbox" class="custom-control-input" id="room5" target="roomChk">';
templeteHTML += '                                <label class="custom-control-label" for="room5">방5개</label>';
templeteHTML += '                            </div>';
templeteHTML += '                        </div>';
templeteHTML += '                    </div>';
templeteHTML += '                    <hr class="mb-4">';
templeteHTML += '                    <button class="btn btn-primary" type="button" id="startBot" disabled="true"> Start Bot </button>';
templeteHTML += '                    <button class="btn btn-danger" type="button" id="stopBot" disabled="true"> Stop Bot </button>';
templeteHTML += '                    <button class="btn btn-warning" type="button" id="resetBot" disabled="true"> Reset Bot </button>';
templeteHTML += '                </form>';
templeteHTML += '            </div>';
templeteHTML += '        </div>';
templeteHTML += '        <div class="row " id="resultWrap" style="margin-top:20px;overflow: auto;display:none;">';
templeteHTML += '            <div style="padding:15px;">';
templeteHTML += '               <div class="custom-control custom-checkbox" style="margin-bottom: 10px;">';
templeteHTML += '                   <input type="checkbox" class="custom-control-input" id="isExcelRow">';
templeteHTML += '                   <label class="custom-control-label" for="isExcelRow">단지간 Row 생성</label>';
templeteHTML += '               </div>';
templeteHTML += '                <button type="button" class="btn btn-info" id="createTable">데이터 테이블 만들기</button>';
templeteHTML += '                <button type="button" class="btn btn-success" id="exportExcel">엑셀 데이터 내려받기</button>';
templeteHTML += '            </div>';
templeteHTML += '        </div>';
templeteHTML += '        <div class="row " style="margin-top:20px;overflow: auto;height:100%;">';
templeteHTML += '            <div class="table-responsive" id="tableWrap" style="max-height:900px;min-width:3500px;font-size:12px;">';
templeteHTML += '            </div>';
templeteHTML += '        </div>';
templeteHTML += '    </div>';
